### ISSUE TITLE
error while starting up

### ISSUE THREAD

**Issue by freakyy85** [webbukkit/Dynmap-GriefPrevention#15]
[18:11:36] [Server thread/WARN]: [Dynmap-GriefPrevention] Task #120 for Dynmap-GriefPrevention v0.80 generated an exception
java.lang.NullPointerException
        at org.dynmap.griefprevention.DynmapGriefPreventionPlugin.handleClaim(DynmapGriefPreventionPlugin.java:212) ~[?:?]
        at org.dynmap.griefprevention.DynmapGriefPreventionPlugin.updateClaims(DynmapGriefPreventionPlugin.java:268) ~[?:?]
        at org.dynmap.griefprevention.DynmapGriefPreventionPlugin.access$000(DynmapGriefPreventionPlugin.java:33) ~[?:?]
        at org.dynmap.griefprevention.DynmapGriefPreventionPlugin$GriefPreventionUpdate.run(DynmapGriefPreventionPlugin.java:100) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c46583f-0643caa]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c46583f-0643caa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-c46583f-0643caa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-0643caa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-0643caa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-0643caa]
        at java.lang.Thread.run(Thread.java:722) [?:1.7.0]

**Comment by kman3107** [comment]
I get the exact same error except mine say 'Task #21'. Have anyone looked into this or know where I should start looking to figure this out? Thanks.
